import type { BaselineDiff } from './baseline.js';
import type { HealthFinding } from './health-analyzer.interface.js';
import {
  formatBaselineDeltaPlain,
  parseDetailSegments,
  PASSING_PLACEHOLDERS,
  tensionShortLabel,
  TENSION_SUBTITLES,
} from './health-reporter.js';
import type { ModuleTensionSummary } from './tension-clusterer.js';

function severityEmoji(severity: string): string {
  if (severity === 'critical') {
    return '🔴';
  }

  if (severity === 'warning') {
    return '🟡';
  }

  return '✅';
}

function formatTypesColumn(cluster: ModuleTensionSummary): string {
  return cluster.tensions
    .map((tension) => `${severityEmoji(tension.severity)} ${tensionShortLabel(tension.type)}`)
    .join(' · ');
}

function formatFindingSubtitle(finding: HealthFinding): string {
  const parsedSegments = parseDetailSegments(finding.detail);

  if (parsedSegments !== null) {
    return `${parsedSegments.length} competing approaches detected:`;
  }

  return TENSION_SUBTITLES[finding.tensionType] ?? finding.detail;
}

function renderDetailBody(finding: HealthFinding): string {
  const parsedSegments = parseDetailSegments(finding.detail);
  const lines: string[] = [];

  lines.push(formatFindingSubtitle(finding));
  lines.push('');

  if (parsedSegments !== null) {
    for (const segment of parsedSegments) {
      const suffix = segment.dominant ? '(dominant)' : '← non-dominant';
      lines.push(`- \`${segment.label}\` — ${segment.percentage}% ${suffix}`);
    }
  } else {
    lines.push(finding.detail);
  }

  lines.push('');
  lines.push(`Affected modules: ${finding.module}`);

  if (finding.affectedFiles !== undefined && finding.affectedFiles.length > 0) {
    lines.push('');
    lines.push('Affected files:');
    for (const file of finding.affectedFiles) {
      lines.push(`- \`${file}\``);
    }
  }

  return lines.join('\n');
}

function renderModuleTable(clusters: ModuleTensionSummary[]): string {
  if (clusters.length === 0) {
    return '';
  }

  const rows = clusters.map(
    (cluster) => `| ${cluster.module} | ${cluster.tensionCount} | ${formatTypesColumn(cluster)} |`,
  );

  return ['| Module | Tensions | Types |', '|--------|----------|-------|', ...rows].join('\n');
}

function renderFindingDetails(finding: HealthFinding, isNew: boolean): string {
  const severityLabel = finding.severity === 'critical' ? 'CRITICAL' : 'WARNING';
  const newSuffix = isNew ? ' [NEW]' : '';
  const summary = `${finding.title} · ${severityLabel}${newSuffix}`;

  return `<details>
<summary>${summary}</summary>

${renderDetailBody(finding)}
</details>`;
}

function renderTensionsSection(findings: HealthFinding[], diff: BaselineDiff | null): string {
  if (findings.length === 0) {
    return '';
  }

  const newTensionTypes = new Set(diff?.newTensions.map((finding) => finding.tensionType) ?? []);
  const sortedFindings = [...findings].sort((a, b) => {
    if (a.severity !== b.severity) {
      return a.severity === 'critical' ? -1 : 1;
    }

    return a.title.localeCompare(b.title);
  });

  return sortedFindings
    .map((finding) => renderFindingDetails(finding, newTensionTypes.has(finding.tensionType)))
    .join('\n\n');
}

function renderPassingSection(): string {
  return `✅ Passing: ${PASSING_PLACEHOLDERS.join(' · ')}`;
}

function formatScoreDelta(diff: BaselineDiff | null): string {
  if (diff === null) {
    return '';
  }

  const delta = formatBaselineDeltaPlain(diff);

  if (delta === '' || delta === 'no change since last scan') {
    return '';
  }

  return ` ${delta}`;
}

export function buildHealthComment(
  findings: HealthFinding[],
  clusters: ModuleTensionSummary[],
  score: number,
  diff: BaselineDiff | null,
): string {
  const delta = formatScoreDelta(diff);
  const header = `## 🏗️ Architecture Health · score: ${score}/100${delta}`;
  const summary =
    findings.length === 0
      ? '> No architectural tensions detected'
      : `> ${findings.length} tension${findings.length === 1 ? '' : 's'} detected across ${clusters.length} module${clusters.length === 1 ? '' : 's'}`;

  const sections = [header, '', summary, ''];

  const moduleTable = renderModuleTable(clusters);

  if (moduleTable !== '') {
    sections.push(moduleTable, '');
  }

  const tensionsSection = renderTensionsSection(findings, diff);

  if (tensionsSection !== '') {
    sections.push(tensionsSection, '');
  }

  sections.push(renderPassingSection(), '', '---', '<sub>Generated by pr-sanity · [view full report]()</sub>');

  return sections.join('\n');
}
